language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - jruby-9.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.2
    - rvm: ruby-head
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  code_climate:
    repo_token:
      secure: Y6i7YGM0oHdDYtKkABGWIxdQL943brOJaFcU2iWSp7oMczQ/Ss4udpm9o11O2zo4WqrHu6E3GrAT1us+FZLWB71hC6PeClluh3ndhD131AnS3yRFhRPMlDYxdSEOfMZhQwdY8E1EUdj3Dpk0UF7Bwxnw/PqAt5AHZ3EC5e4DJJ0=
deploy:
  provider: rubygems
  api_key:
    secure: "NM3wz/isaEbJeepeTY/GIj7Vo+EkKeKljXY7M97ekXw0T+S/E5AjVwJSPHU+NFCdu5jnTibtIhXda8TTOyHaPwo45E18wCFVvGc2q9skAo6UBYdtM5TfKNiyDFVIIyGiItM1rUVxKY4neBew3Ys3RQFUrIAeuv6dDWfZ9YDiDlo="
  on:
    rvm: 2.5
    tags: true
