= Asciidoctor::DocTest Changelog
:repo-uri: https://github.com/asciidoctor/asciidoctor-doctest
:commit-uri: {repo-uri}/commit
:issue-uri: {repo-uri}/issues

This document provides a high-level view of the changes introduced in DocTest by release.
For a detailed view of what has changed, refer to the {repo-uri}/commits/master[commit history] on GitHub.


== 1.5.2.0 (2015-04-04)

Improvements::
  * Update https://github.com/threedaymonk/htmlbeautifier[htmlbeautifier] to 1.0.0 and remove workaround in `html/html_beautifier` [{commit-uri}/6caafb0[6caafb0]].
  * Extract formatting (serialization) of example’s options into `BaseExamplesSuite#format_options` to be reusable [{commit-uri}/c4d779c[c4d779c]].
  * Implement serialization of examples suite into AsciiDoc [{commit-uri}/900aab8[900aab8]].
  * Replace custom core extensions, ActiveSupport and Colorize with https://github.com/jirutka/corefines[Corefines]. This also means that refinements will be used instead of global monkey-patching, when running on Ruby that supports refinements (currently MRI ≥2.1.0). [{commit-uri}/50e05c1[50e05c1], {commit-uri}/2f4a42e[2f4a42e]]

Bug fixes::
  * Fix implementation of `eql?` and `hash` in BaseExample [{commit-uri}/c27615b[c27615b]].


== 1.5.1.2 (2015-01-03)

Improvements::
  * Support for MRI 2.0.0 and JRuby 9000-dev [{commit-uri}/8908c5d[8908c5d], {commit-uri}/748d54a[748d54a]].


== 1.5.1.1 (2014-12-30)

Bug fixes::
  * Avoid setting `backend_name` to an empty string.
    When there’s an empty string and code highlighter is set to Pygments or CodeRay, then Asciidoctor doesn’t highlight listings at all. [{commit-uri}/bf5f077[bf5f077]]
  * Update https://github.com/threedaymonk/htmlbeautifier[htmlbeautifier] to 0.0.11 that doesn’t modify content of `pre` element and adds newlines around block elements. {issue-uri}/3[#3] [{commit-uri}/4aaa137[4aaa137]]


== 1.5.1 (2014-12-29)

Improvements::
  * Rename parameter `renderer_opts` to `converter_opts` and method `render` to `convert` to be consistent with Asciidoctor (old names are aliased for now). {issue-uri}/2[#2] [{commit-uri}/97c06af[97c06af]]
  * Rename `to_s` to `content_pretty` in BaseExample and make alias. [{commit-uri}/3b610e2[3b610e2]]

Bug fixes::
  * Allow to modify default `examples_path` in GeneratorTask (was frozen). [{commit-uri}/7251e6c[7251e6c]]
  * Fix `template_dirs` validation and default `backend_name` in AsciidocRenderer. [{commit-uri}/2a4413d[2a4413d]]
  * Beautify generated HTML examples. [{commit-uri}/e9d42be[e9d42be]]
  * Fix Generator to not lose description of the updated example. [{commit-uri}/0d2f4ee[0d2f4ee]]

Tests::
  * Add end-to-end integration tests using Cucumber.
  * Increase (unit) test coverage from 84.2% to 88.5%.

Known issues::
  * HTML beautifier doesn’t work as expected. {issue-uri}/3[#3]


== 1.5.0 (2014-12-09)

The first stable release.
