require 'asciidoctor/doctest'
require 'rake/testtask'
require 'tilt'

DocTest::GeneratorTask.new(:generate) do |task|
  task.output_suite = DocTest::HTML::ExamplesSuite.new(examples_path: 'examples/html')
  task.examples_path = 'examples/asciidoc'
  task.converter_opts[:template_dirs] = 'templates'
end

Rake::TestTask.new(:test) do |task|
  task.description = 'Run tests for custom HTML backend'
  task.pattern = 'test/html_test.rb'
  task.libs << 'test'
end
